version: 2
jobs:
  test:
    working_directory: ~/testLuizaLabs
    docker:
      - image: node:10.11.0

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run linter
          command: npm run eslint
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  verify:
    jobs:
      - test